name: MaterialChicks
version: '${project.version}'
author: BlameBert
description: Island Generation
main: com.berttowne.materialchicks.MaterialChicks
loader: com.berttowne.materialchicks.MaterialChicksLoader
bootstrapper: com.berttowne.materialchicks.MaterialChicksBootstrapper
api-version: '1.21.5'
folia-supported: true